#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

branch="$(git rev-parse --abbrev-ref HEAD)"
if [ "$branch" = "main" ] || [ "$branch" = "master" ]; then
  echo "❌ You are on '$branch' branch. You can't commit directly here. Please create a new feature branch."
  exit 1
fi

npx lint-staged
